apiVersion: apps/v1
kind: Deployment
metadata:
  name: churros-api
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: 'kubernetes.io/hostname'
                labelSelector:
                  matchLabels:
                    app: churros-api
      containers:
        - image: registry.inpt.fr/churros/churros/api:latest
          imagePullPolicy: IfNotPresent
          name: api
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              scheme: HTTP
              path: /
              port: 4000
          resources:
            requests:
              memory: '512Mi'
              cpu: '300m'
            limits:
              memory: '1024Mi'
              cpu: '800m'
          env:
            - name: DATABASE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: churros-postgresql-app
                  key: uri
            - name: DATABASE_URL
              value: $(DATABASE_BASE_URL)?pool_timeout=60
          envFrom:
            - configMapRef:
                name: churros-config
            - secretRef:
                name: churros-secrets
      initContainers:
        - image: registry.inpt.fr/churros/churros/prisma:latest
          name: migrator
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: churros-postgresql-app
                  key: uri
            - name: DATABASE_URL
              value: $(DATABASE_BASE_URL)?pool_timeout=60
