/**
 * @file Automatically generated by barrelsby.
 */

export * from './major.teaching-units.js';
export * from './minor.teaching-units.js';
export * from './mutation.update-subjects-exam-dates.js';
export * from './query.major.js';
export * from './query.majors.js';
export * from './query.minor.js';
export * from './query.minors-of-major.js';
export * from './query.minors.js';
export * from './query.subject.js';
export * from './query.subjects-of-major.js';
export * from './query.subjects-of-minor.js';
export * from './query.subjects.js';
