# yaml-language-server: $schema=https://raw.githubusercontent.com/graphinx/graphinx/v0.12.0/config.schema.json
template: graphinx/templates/default#v0.12.0

schema:
  static: ../app/schema.graphql

branding:
  logo:
    dark: https://churros.inpt.fr/logo-masked.png
    light: /logo-masked-dark.png # TODO put in on churros.inpt.fr logo-masked-dark.png
  name: Churros API

pages: ./docs
static: ./docs
description: ./README.md

environment:
  PUBLIC_API_URL: https://churros.inpt.fr/graphql
  PUBLIC_API_WEBSOCKET_URL: wss://churros.inpt.fr/graphql
  CURRENT_COMMIT: '72ad22314b5c607b60a9011f8884de8a929c28fd'
  CURRENT_VERSION: 'dev'
  CURRENT_COMMIT_SHORT: '72ad223'
  PUBLIC_AUTH_TYPE: UserPassword # available: OAuth (PKCE flow), OpenID, UserPassword, Token, None (default)
  PUBLIC_AUTH_HEADER: Bearer # available: Bearer (for all AUTH_TYPEs), Basic (for UserPassword, takes the base64 of the form `username:password`), plain (for all types, just puts the token as is)
  PUBLIC_AUTH_QUERY: |
    mutation APIDocsLogin($user: String!, $password: String!) {
      login(email: $user, password: $password) {
          ...on MutationLoginSuccess {
              data {
                  token
              }
          }
      }
    }
  PUBLIC_AUTH_QUERY_PATH: login.data.token
  PUBLIC_AUTH_LOGOUT_QUERY: 'mutation APIDocsLogout { logout }'

modules:
  docs: src/modules/[module]/README.md
  icons: src/modules/[module]/icon.svg
  fallback: global
  filesystem:
    - src/modules/[module]/resolvers/[parent].[fieldname].ts
    - src/modules/[module]/types/[typename].ts
  mapping:
    ID: global
    Node: global
    PageInfo: global
    Error: global
    ErrorInterface: global
    ZodFieldError: global
    NotFoundError: global
    # FIXME: Graphinx cannot infer when success datatype is String
    EventBookingsCsv{Result,Success}: ticketing
  order:
    - global
    - users
    - groups
    - posts
    - events
    - ticketing
    - shop
    - forms
    - documents
    - themes
    - pictures
    - profiles
    - notifications
    - services
    - student-associations
    - pages
    - schools
    - curriculum
    - comments
    - reactions
    - links
    - announcements
    - payments
    - gitlab
    - changelogs
    - logs
    - health-checks

footer: |
  <p>
    Churros API, version %$CURRENT_VERSION% (at
    <a href="https://git.inpt.fr/inp-net/churros/-/commit/%$CURRENT_COMMIT%">
      <code class="no-color">%$CURRENT_COMMIT_SHORT%</code></a
    >)
  </p>
  <a class="net7" href="https://net7.dev">
    Made with <span style:color="red"><strong>&lt;3</strong></span> by
    <img data-dark src="https://churros.inpt.fr/storage/groups/dark/net7-n7.png" alt="net7" />
    <img data-light src="https://churros.inpt.fr/storage/groups/net7-n7.png" alt="net7" />
  </a>

  <style>
    .net7 {
      display: flex;
      flex-wrap: wrap;
      column-gap: 1ch;
      align-items: center;
      justify-content: center;
      margin-top: 5rem;
      font-family: 'Space Mono', monospace;
      color: var(--fg);
      text-decoration: none;
      border-radius: 2rem;
      transition: box-shadow 0.2s ease;
    }

    .net7:hover,
    .net7:focus-visible {
      box-shadow: 0 0 50px 3px color-mix(in oklab, var(--fg) 15%, var(--shadow));
    }

    .net7 img {
      width: 100px;
      margin-left: 1em;
    }

    [data-theme=light] .net7 img[data-dark] {
      display: none;
    }

    [data-theme=dark] .net7 img[data-light] {
      display: none;
    }
  </style>
