.volta:
  image: marcaureln/volta:2.0.2-slim
  before_script:
    - apt update && apt install -y git
    - yarn config set enableGlobalCache false
    - yarn config set enableImmutableInstalls true
    - yarn install

  cache:
    paths:
      - .yarn/cache/

pages:
  stage: deploy
  extends: .volta
  rules:
    # build on tags, but not pre-releases
    - if: $CI_COMMIT_TAG =~ /^@churros\/api@(\d+\.\d+\.\d+)/
    # allow manual triggers
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    - yarn workspace @churros/api install --immutable
    - yarn generate-buildinfo
    - yarn workspace @churros/api graphinx build ../../public
  artifacts:
    paths:
      - public
