apiVersion: batch/v1
kind: CronJob
metadata:
  name: churros-sync
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync
              image: registry.inpt.fr/churros/churros/sync:latest
              imagePullPolicy: Always
              env:
                - name: DATABASE_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: churros-postgresql-app
                      key: uri
                - name: DATABASE_URL
                  value: $(DATABASE_BASE_URL)?pool_timeout=60
              envFrom:
                - configMapRef:
                    name: churros-config
                - secretRef:
                    name: churros-secrets
          restartPolicy: Never
