/**
 * @file Automatically generated by barrelsby.
 */

export * from "./old-majors.js";
export * from "./old-minors.js";
export * from "./old-subjects.js";
export * from "./old-teaching-units.js";
export * from "./resolvers/index.js";
export * from "./types/index.js";
export * from "./utils/index.js";
