#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --name-only HEAD@{1} HEAD | grep "yarn.lock" &> /dev/null; then
  echo 🔒 yarn.lock changed, you should update dependencies by running:
  echo yarn install
fi

if git diff --name-only HEAD@{1} HEAD | grep "packages/db/prisma/schema.prisma" &> /dev/null; then
  echo 🗃️ database schema changed, you should migrate and re-seed the local database by running:
  echo yarn reset
fi
