#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# yarn.lock -> yarn install
if git diff --name-only HEAD@{1} HEAD | grep "yarn.lock" &> /dev/null; then
  echo 🔒 yarn.lock changed, you should update dependencies by running:
  echo yarn install
fi

# packages/db/prisma/schema.prisma -> yarn reset
if git diff --name-only HEAD@{1} HEAD | grep "packages/db/prisma/schema.prisma" &> /dev/null; then
  echo 🗃️ database schema changed, you should migrate and re-seed the local database by running:
  echo yarn reset
fi

# .env.example -> yarn sync-with-example-env
if git diff --name-only HEAD@{1} HEAD | grep ".env.example" &> /dev/null; then
  echo 📝 .env.example changed, you should sync your .env file with .env.example by running:
  echo yarn sync-with-example-env
  echo "(note: this will not touch any existing values in your .env file, don't worry)"
fi
